import { afterEach, describe, expect, test, vi } from "vitest";
import {
	createGeminiRequestBody,
	GEMINI_MODEL,
	GeminiApiError,
	GeminiClient,
	GeminiIncompleteResponseError,
	isGeminiStreamingFallbackEligible,
} from "@/lib/ai/geminiClient";

afterEach(() => {
	vi.unstubAllGlobals();
});

describe("createGeminiRequestBody", () => {
	test("keeps system instructions out of user conversation content", () => {
		const body = createGeminiRequestBody([
			{ role: "system", parts: [{ text: "Follow the supplied data." }] },
			{ role: "user", parts: [{ text: "Explain this metric." }] },
		]);

		expect(body.systemInstruction).toEqual({ parts: [{ text: "Follow the supplied data." }] });
		expect(body.contents).toEqual([{ role: "user", parts: [{ text: "Explain this metric." }] }]);
		expect(body.generationConfig).toEqual({
			maxOutputTokens: 4096,
			thinkingConfig: { thinkingLevel: "low" },
		});
		expect(body.generationConfig).not.toHaveProperty("temperature");
		expect(body.generationConfig).not.toHaveProperty("topK");
		expect(body.generationConfig).not.toHaveProperty("topP");
	});
});

describe("GeminiClient.parseSseBuffer", () => {
	test("preserves an incomplete event for the next transport chunk", () => {
		const first = GeminiClient.parseSseBuffer(
			'data: {"candidates":[{"content":{"parts":[{"text":"Hel',
		);
		expect(first.texts).toEqual([]);

		const second = GeminiClient.parseSseBuffer(`${first.remainder}lo"}]}}]}\n\n`);
		expect(second.texts).toEqual(["Hello"]);
		expect(second.remainder).toBe("");
	});

	test("parses multiple complete SSE events", () => {
		const event = (text: string) =>
			`data: ${JSON.stringify({ candidates: [{ content: { parts: [{ text }] } }] })}\n\n`;
		const parsed = GeminiClient.parseSseBuffer(`${event("one")}${event("two")}`);

		expect(parsed.texts).toEqual(["one", "two"]);
	});

	test("flushes a final event without a trailing separator", () => {
		const event = `data: ${JSON.stringify({
			candidates: [{ content: { parts: [{ text: "final" }] } }],
		})}`;

		expect(GeminiClient.parseSseBuffer(event, true)).toEqual({
			texts: ["final"],
			remainder: "",
		});
	});

	test("ignores terminal and malformed provider events", () => {
		const parsed = GeminiClient.parseSseBuffer(
			'data: [DONE]\n\ndata: not-json\n\ndata: {"candidates": []}',
			true,
		);
		expect(parsed).toEqual({ texts: [], remainder: "" });
		expect(GeminiClient.parseStreamChunk("not-json")).toBeNull();
	});
});

describe("GeminiClient provider requests", () => {
	test("requests and returns an SSE response body", async () => {
		const body = new ReadableStream<Uint8Array>();
		const fetchMock = vi.fn().mockResolvedValue(new Response(body));
		vi.stubGlobal("fetch", fetchMock);
		const client = new GeminiClient("secret-key");

		expect(
			await client.generateStreamingContent([{ role: "user", parts: [{ text: "Hello" }] }]),
		).toBe(body);
		expect(fetchMock).toHaveBeenCalledWith(
			expect.stringContaining(":streamGenerateContent?alt=sse"),
			expect.objectContaining({
				headers: expect.objectContaining({ "x-goog-api-key": "secret-key" }),
			}),
		);
	});

	test("rejects failed and empty streaming responses", async () => {
		const client = new GeminiClient("secret-key", { attempts: 1 });
		vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(null, { status: 429 })));
		await expect(client.generateStreamingContent([])).rejects.toBeInstanceOf(GeminiApiError);

		vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(null, { status: 200 })));
		await expect(client.generateStreamingContent([])).rejects.toThrow(
			"Gemini returned an empty response body",
		);
	});

	test("returns generated text and rejects invalid responses", async () => {
		const client = new GeminiClient("secret-key", { attempts: 1 });
		const fetchMock = vi
			.fn()
			.mockResolvedValueOnce(
				Response.json({ candidates: [{ content: { parts: [{ text: "Answer" }] } }] }),
			)
			.mockResolvedValueOnce(Response.json({ candidates: [] }))
			.mockResolvedValueOnce(new Response(null, { status: 503 }));
		vi.stubGlobal("fetch", fetchMock);

		await expect(client.generateContent([])).resolves.toBe("Answer");
		await expect(client.generateContent([])).rejects.toThrow("No content generated by Gemini");
		await expect(client.generateContent([])).rejects.toMatchObject({ status: 503 });
		expect(fetchMock.mock.calls[0]?.[0]).toContain(`/models/${GEMINI_MODEL}:generateContent`);
	});

	test("joins all non-thinking text parts", async () => {
		vi.stubGlobal(
			"fetch",
			vi.fn().mockResolvedValue(
				Response.json({
					candidates: [
						{
							finishReason: "STOP",
							content: {
								parts: [
									{ text: "internal", thought: true },
									{ text: "Complete " },
									{ text: "answer" },
								],
							},
						},
					],
				}),
			),
		);

		await expect(new GeminiClient("secret-key", { attempts: 1 }).generateContent([])).resolves.toBe(
			"Complete answer",
		);
	});

	test("rejects partial text when Gemini reaches an output boundary", async () => {
		vi.stubGlobal(
			"fetch",
			vi.fn().mockResolvedValue(
				Response.json({
					candidates: [
						{
							finishReason: "MAX_TOKENS",
							content: { parts: [{ text: "A report cut off mid-sentence," }] },
						},
					],
				}),
			),
		);

		await expect(
			new GeminiClient("secret-key", { attempts: 1 }).generateContent([]),
		).rejects.toBeInstanceOf(GeminiIncompleteResponseError);
	});

	test("retries a transient provider response before succeeding", async () => {
		const fetchMock = vi
			.fn()
			.mockResolvedValueOnce(new Response(null, { status: 503 }))
			.mockResolvedValueOnce(
				Response.json({ candidates: [{ content: { parts: [{ text: "Recovered" }] } }] }),
			);
		vi.stubGlobal("fetch", fetchMock);
		const client = new GeminiClient("secret-key");

		await expect(client.generateContent([])).resolves.toBe("Recovered");
		expect(fetchMock).toHaveBeenCalledTimes(2);
	});

	test("does not amplify provider rate limits", async () => {
		const fetchMock = vi.fn().mockResolvedValue(new Response(null, { status: 429 }));
		vi.stubGlobal("fetch", fetchMock);
		const client = new GeminiClient("secret-key");

		await expect(client.generateContent([])).rejects.toMatchObject({ status: 429 });
		expect(fetchMock).toHaveBeenCalledTimes(1);
	});

	test("propagates caller cancellation without starting another attempt", async () => {
		const controller = new AbortController();
		const fetchMock = vi.fn(
			(_url: string, init: RequestInit) =>
				new Promise<never>((_, reject) => {
					init.signal?.addEventListener("abort", () => reject(init.signal?.reason));
				}),
		);
		vi.stubGlobal("fetch", fetchMock);
		const client = new GeminiClient("secret-key", { attempts: 2 });
		const request = client.generateContent([], {}, { signal: controller.signal });

		controller.abort(new DOMException("client disconnected", "AbortError"));

		await expect(request).rejects.toMatchObject({ name: "AbortError" });
		expect(fetchMock).toHaveBeenCalledTimes(1);
	});
});

describe("Gemini streaming fallback policy", () => {
	test("allows transport and protocol failures", () => {
		expect(isGeminiStreamingFallbackEligible(new TypeError("network unavailable"))).toBe(true);
		expect(isGeminiStreamingFallbackEligible(new Error("empty response body"))).toBe(true);
	});

	test("does not amplify provider rejections or caller cancellation", () => {
		expect(isGeminiStreamingFallbackEligible(new GeminiApiError(429, "Too Many Requests"))).toBe(
			false,
		);
		expect(isGeminiStreamingFallbackEligible(new GeminiApiError(400, "Bad Request"))).toBe(false);

		const controller = new AbortController();
		controller.abort();
		expect(
			isGeminiStreamingFallbackEligible(new Error("stream interrupted"), controller.signal),
		).toBe(false);
	});
});
