import { MetricDefinition } from "@/lib/types";

export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  "Market Cap": {
    metric_display: "**Market Capitalization**",
    definition: "The total market value of a company's outstanding shares, calculated by multiplying share price by the number of shares.",
    explanation: "It represents the size of a company and helps investors categorize stocks into large-cap, mid-cap, or small-cap investments, each with different risk and growth characteristics.",
    learn_more_url: "https://www.investopedia.com/terms/m/marketcapitalization.asp"
  },
  
  "Enterprise Value": {
    metric_display: "**Enterprise Value**",
    definition: "The total value of a company including debt, calculated as market cap plus total debt minus cash and cash equivalents.",
    explanation: "It provides a more complete picture of a company's value than market cap alone, especially useful for comparing companies with different capital structures.",
    learn_more_url: "https://www.investopedia.com/terms/e/enterprisevalue.asp"
  },
  
  "Shares Outstanding": {
    metric_display: "**Shares Outstanding**",
    definition: "The total number of shares of a company that are currently owned by all shareholders, including restricted shares.",
    explanation: "This number is used to calculate key metrics like earnings per share and market capitalization, and changes when companies issue new shares or buy back existing ones.",
    learn_more_url: "https://www.investopedia.com/terms/o/outstandingshares.asp"
  },
  
  "Revenue": {
    metric_display: "**Revenue**",
    definition: "The total amount of income generated by a company from its business operations over a specific period.",
    explanation: "Also called sales or turnover, it's the top line of the income statement and indicates a company's ability to generate income from its core business activities.",
    learn_more_url: "https://www.investopedia.com/ask/answers/052215/why-ttm-trailing-twelve-months-important-finance.asp"
  },
  
  "Employees": {
    metric_display: "**Employee Count**",
    definition: "The total number of full-time equivalent employees working for the company.",
    explanation: "This metric helps assess company size, operational scale, and can be used to calculate productivity ratios like revenue per employee.",
    learn_more_url: "https://www.investopedia.com/terms/r/revenueperemployee.asp"
  },
  
  "P/E Ratio": {
    metric_display: "**Price-to-Earnings Ratio**",
    definition: "A valuation metric that compares a company's current share price to its earnings per share.",
    explanation: "It shows how much investors are willing to pay for each dollar of earnings, helping assess if a stock is overvalued or undervalued relative to its profits.",
    learn_more_url: "https://www.investopedia.com/terms/p/price-earningsratio.asp"
  },
  
  "Forward P/E": {
    metric_display: "**Forward Price-to-Earnings Ratio**",
    definition: "A valuation metric using projected earnings for the next 12 months instead of historical earnings.",
    explanation: "It provides a forward-looking view of valuation and is often considered more relevant than historical P/E for investment decisions.",
    learn_more_url: "https://www.investopedia.com/terms/f/forwardpe.asp"
  },
  
  "P/B Ratio": {
    metric_display: "**Price-to-Book Ratio**",
    definition: "A valuation ratio comparing a company's market value to its book value (assets minus liabilities).",
    explanation: "It indicates whether a stock is trading above or below its accounting value, particularly useful for asset-heavy businesses and value investing.",
    learn_more_url: "https://www.investopedia.com/terms/p/price-to-bookratio.asp"
  },
  
  "P/S Ratio": {
    metric_display: "**Price-to-Sales Ratio**",
    definition: "A valuation metric that compares a company's stock price to its revenue per share.",
    explanation: "Useful for evaluating companies with little or no earnings, especially growth companies and those in cyclical industries.",
    learn_more_url: "https://www.investopedia.com/terms/p/price-to-salesratio.asp"
  },
  
  "EV/Sales": {
    metric_display: "**Enterprise Value to Sales**",
    definition: "A valuation multiple that compares enterprise value to annual sales revenue.",
    explanation: "It's useful for comparing companies with different capital structures since it accounts for debt, making it more comprehensive than P/S ratio.",
    learn_more_url: "https://www.investopedia.com/terms/e/enterprisevaluesales.asp"
  },
  
  "EV/EBITDA": {
    metric_display: "**Enterprise Value to EBITDA**",
    definition: "A valuation multiple comparing enterprise value to earnings before interest, taxes, depreciation, and amortization.",
    explanation: "Widely used in corporate finance for comparing companies across different industries and capital structures, as it focuses on operational performance.",
    learn_more_url: "https://www.investopedia.com/terms/e/ev-ebitda.asp"
  },
  
  "PEG Ratio": {
    metric_display: "**Price/Earnings to Growth Ratio**",
    definition: "A valuation metric that adjusts the P/E ratio by the company's earnings growth rate.",
    explanation: "It helps identify whether a stock's valuation is justified by its growth prospects, with a PEG below 1.0 often considered attractive.",
    learn_more_url: "https://www.investopedia.com/terms/p/pegratio.asp"
  },
  
  "Gross Margin": {
    metric_display: "**Gross Profit Margin**",
    definition: "The percentage of revenue remaining after subtracting the cost of goods sold.",
    explanation: "It measures a company's pricing power and operational efficiency in producing its goods or services, with higher margins indicating better profitability.",
    learn_more_url: "https://www.investopedia.com/terms/g/grossmargin.asp"
  },
  
  "EBITDA Margin": {
    metric_display: "**EBITDA Margin**",
    definition: "Earnings before interest, taxes, depreciation, and amortization as a percentage of revenue.",
    explanation: "It measures operational profitability by excluding non-operational expenses and is useful for comparing companies across different tax jurisdictions and capital structures.",
    learn_more_url: "https://www.investopedia.com/terms/e/ebitda-margin.asp"
  },
  
  "Operating Margin": {
    metric_display: "**Operating Margin**",
    definition: "Operating income as a percentage of revenue, showing profitability from core business operations.",
    explanation: "It excludes non-operating income and expenses, providing insight into management's ability to control costs and generate profits from operations.",
    learn_more_url: "https://www.investopedia.com/terms/o/operatingmargin.asp"
  },
  
  "Net Margin": {
    metric_display: "**Net Profit Margin**",
    definition: "Net income as a percentage of revenue, representing the bottom-line profitability.",
    explanation: "It shows how much profit a company keeps from each dollar of revenue after all expenses, taxes, and interest, indicating overall financial efficiency.",
    learn_more_url: "https://www.investopedia.com/terms/n/net_margin.asp"
  },
  
  "ROA": {
    metric_display: "**Return on Assets**",
    definition: "A profitability ratio measuring how efficiently a company uses its assets to generate earnings.",
    explanation: "It indicates management's effectiveness at using company assets to create profits, with higher ROA suggesting better asset utilization.",
    learn_more_url: "https://www.investopedia.com/terms/r/returnonassets.asp"
  },
  
  "ROE": {
    metric_display: "**Return on Equity**",
    definition: "A measure of financial performance calculated by dividing net income by shareholders' equity.",
    explanation: "It shows how effectively management is using shareholders' investments to generate profits, making it a key metric for equity investors.",
    learn_more_url: "https://www.investopedia.com/terms/r/returnonequity.asp"
  },
  
  "Total Cash": {
    metric_display: "**Total Cash and Cash Equivalents**",
    definition: "The sum of cash and short-term, highly liquid investments that can be quickly converted to cash.",
    explanation: "It provides financial flexibility, allowing companies to weather downturns, invest in opportunities, or return money to shareholders through dividends or buybacks.",
    learn_more_url: "https://www.investopedia.com/terms/c/cashandcashequivalents.asp"
  },
  
  "Total Debt": {
    metric_display: "**Total Debt**",
    definition: "The sum of all short-term and long-term debt obligations a company owes to creditors.",
    explanation: "It affects financial risk and interest expenses, with high debt levels potentially limiting financial flexibility but also enabling growth and tax benefits.",
    learn_more_url: "https://www.investopedia.com/terms/d/debtratio.asp"
  },
  
  "Debt-to-Equity": {
    metric_display: "**Debt-to-Equity Ratio**",
    definition: "A leverage ratio comparing total debt to shareholders' equity, measuring financial leverage.",
    explanation: "It indicates how much debt a company uses to finance operations relative to equity, with higher ratios suggesting greater financial risk but potential for higher returns.",
    learn_more_url: "https://www.investopedia.com/terms/d/debtequityratio.asp"
  },
  
  "Revenue Growth": {
    metric_display: "**Revenue Growth Rate**",
    definition: "The percentage increase in revenue compared to the previous period, typically measured annually.",
    explanation: "It indicates business expansion and market demand for the company's products or services, with consistent growth often signaling competitive strength.",
    learn_more_url: "https://www.investopedia.com/terms/q/quarterlyrevenuegrowth.asp"
  },
  
  "Earnings Growth": {
    metric_display: "**Earnings Growth Rate**",
    definition: "The percentage change in earnings per share compared to the previous period.",
    explanation: "It measures how quickly a company is increasing its profitability, often a key driver of stock price appreciation and investor interest.",
    learn_more_url: "https://www.investopedia.com/terms/p/pegratio.asp"
  },
  
  "Beta": {
    metric_display: "**Beta Coefficient**",
    definition: "A measure of a stock's volatility relative to the overall market, with 1.0 representing market-level volatility.",
    explanation: "Values above 1.0 indicate higher volatility than the market, while below 1.0 suggests lower volatility, helping investors assess risk and expected returns.",
    learn_more_url: "https://www.investopedia.com/terms/b/beta.asp"
  },
  
  "Dividend Yield": {
    metric_display: "**Dividend Yield**",
    definition: "The annual dividend payment as a percentage of the current stock price.",
    explanation: "It shows the income return on investment from dividends alone, popular with income-focused investors seeking regular cash flows from their holdings.",
    learn_more_url: "https://www.investopedia.com/terms/d/dividendyield.asp"
  },
  
  "Dividend Rate": {
    metric_display: "**Dividend Rate**",
    definition: "The total expected dividend payments from an investment expressed on an annualized basis, including any additional non-recurring dividends.",
    explanation: "It represents the actual dollar amount of dividends paid per share annually, calculated by multiplying periodic dividend payments by the number of payment periods in one year.",
    learn_more_url: "https://www.investopedia.com/terms/d/dividendrate.asp"
  },
  
  "Payout Ratio": {
    metric_display: "**Dividend Payout Ratio**",
    definition: "The percentage of earnings paid out as dividends to shareholders.",
    explanation: "It indicates how much of a company's profits are returned to shareholders versus retained for growth, with sustainable ratios typically below 60-80%.",
    learn_more_url: "https://www.investopedia.com/terms/d/dividendpayoutratio.asp"
  },
  
  "Stock Price": {
    metric_display: "**Stock Price**",
    definition: "The current market price per share at which the stock is trading on the exchange.",
    explanation: "It reflects investor sentiment and expectations about the company's future prospects, determined by supply and demand dynamics in the market.",
    learn_more_url: "https://www.investopedia.com/terms/s/stockprice.asp"
  },
  
  "Trading Volume": {
    metric_display: "**Trading Volume**",
    definition: "The total number of shares traded during a specific period, typically measured daily.",
    explanation: "High volume indicates strong investor interest and can confirm price movements, while low volume may suggest uncertainty or lack of conviction in price changes.",
    learn_more_url: "https://www.investopedia.com/terms/v/volume.asp"
  }
};
