environment: production
clusterName: indus-production
vpcId: vpc-replace-production
awsRegion: ca-central-1
roles:
  loadBalancer: arn:aws:iam::444444444444:role/indus-production-load-balancer
  otelCollector: arn:aws:iam::444444444444:role/indus-production-otel-collector
prometheusRemoteWriteUrl: https://aps-workspaces.ca-central-1.amazonaws.com/workspaces/replace-production/api/v1/remote_write
